baseURL = 'https://emert117.github.io/homelab-blog/'
languageCode = 'en-us'
title = 'DevOps@home Blog'
theme = 'terminal'
contentDir = "content"
relativeURLs = true

[params]
  # These are the default terminal colors: 
  # "orange", "blue", "red", "green", "pink", "white"
  themeColor = "orange"

  # The theme uses "posts" as the default content directory name
  contentTypeName = "posts"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'